from __future__ import annotations

import os
from pathlib import Path

APP_DIR = Path(__file__).resolve().parent
BACKEND_DIR = APP_DIR.parent
PROJECT_DIR = BACKEND_DIR.parent

DATA_DIR = BACKEND_DIR / "data"
SEED_DIR = DATA_DIR / "seed"
UPLOADS_DIR = DATA_DIR / "uploads"
WATCH_DIR = DATA_DIR / "watched"
AUDIO_CHUNK_DIR = UPLOADS_DIR / "audio_chunks"
FRAME_STASH_DIR = DATA_DIR / "frames"

DB_PATH = Path(
    os.getenv("SCENECOPILOT_DB_PATH", str(DATA_DIR / "runtime" / "scenecopilot.db"))
)

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "").strip()
ANTHROPIC_MODEL = os.getenv("ANTHROPIC_MODEL", "claude-3-5-sonnet-latest")
ANTHROPIC_VISION_MODEL = os.getenv("ANTHROPIC_VISION_MODEL", ANTHROPIC_MODEL)
ANTHROPIC_DECISION_MODEL = os.getenv("ANTHROPIC_DECISION_MODEL", ANTHROPIC_MODEL)
ANTHROPIC_MAX_TOKENS = int(os.getenv("SCENECOPILOT_ANTHROPIC_MAX_TOKENS", "768"))
ANTHROPIC_IMAGE_MAX_SIDE = int(os.getenv("SCENECOPILOT_ANTHROPIC_IMAGE_MAX_SIDE", "1280"))
ANTHROPIC_IMAGE_JPEG_QUALITY = int(os.getenv("SCENECOPILOT_ANTHROPIC_IMAGE_JPEG_QUALITY", "82"))
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "").strip()
OPENAI_TRANSCRIBE_MODEL = os.getenv("SCENECOPILOT_OPENAI_TRANSCRIBE_MODEL", "gpt-4o-mini-transcribe").strip()
OPENAI_TRANSCRIBE_TIMEOUT_SEC = float(os.getenv("SCENECOPILOT_OPENAI_TRANSCRIBE_TIMEOUT_SEC", "30"))
LOCAL_SPEECH_MODEL = os.getenv("SCENECOPILOT_LOCAL_SPEECH_MODEL", "base.en").strip()
LOCAL_SPEECH_DEVICE = os.getenv("SCENECOPILOT_LOCAL_SPEECH_DEVICE", "cpu").strip()
LOCAL_SPEECH_COMPUTE_TYPE = os.getenv("SCENECOPILOT_LOCAL_SPEECH_COMPUTE_TYPE", "int8").strip()
DEMO_USER_ID = int(os.getenv("SCENECOPILOT_DEMO_USER_ID", "1"))
ENABLE_WATCHER = os.getenv("SCENECOPILOT_ENABLE_WATCHER", "1") != "0"
HOUSEKEEPING_INTERVAL_SEC = float(os.getenv("SCENECOPILOT_HOUSEKEEPING_INTERVAL_SEC", "30"))
MAX_CONCURRENT_RUNS = int(os.getenv("SCENECOPILOT_MAX_CONCURRENT_RUNS", "4"))
MAX_PENDING_RUNS = int(os.getenv("SCENECOPILOT_MAX_PENDING_RUNS", "64"))
TOOL_TIMEOUT_SEC = float(os.getenv("SCENECOPILOT_TOOL_TIMEOUT_SEC", "8"))
EVENT_REPLAY_LIMIT = int(os.getenv("SCENECOPILOT_EVENT_REPLAY_LIMIT", "400"))
EVENT_SESSION_STATE_TTL_SEC = float(os.getenv("SCENECOPILOT_EVENT_SESSION_STATE_TTL_SEC", "300"))
UPLOAD_MAX_BYTES = int(os.getenv("SCENECOPILOT_UPLOAD_MAX_BYTES", str(8 * 1024 * 1024)))
FRAME_STASH_TTL_SEC = float(os.getenv("SCENECOPILOT_FRAME_STASH_TTL_SEC", "45"))
DOC_SEARCH_CACHE_TTL_SEC = float(os.getenv("SCENECOPILOT_DOC_SEARCH_CACHE_TTL_SEC", "30"))
DOC_SEARCH_CACHE_MAX_ITEMS = int(os.getenv("SCENECOPILOT_DOC_SEARCH_CACHE_MAX_ITEMS", "256"))
DOC_CHUNK_SIZE = int(os.getenv("SCENECOPILOT_DOC_CHUNK_SIZE", "120"))
DOC_CHUNK_OVERLAP = int(os.getenv("SCENECOPILOT_DOC_CHUNK_OVERLAP", "24"))
DOC_VECTOR_DIMS = int(os.getenv("SCENECOPILOT_DOC_VECTOR_DIMS", "64"))
ENABLE_EXTERNAL_SEARCH = os.getenv("SCENECOPILOT_ENABLE_EXTERNAL_SEARCH", "1") != "0"
EXTERNAL_SEARCH_PROVIDER = os.getenv("SCENECOPILOT_EXTERNAL_SEARCH_PROVIDER", "wikipedia")
EXTERNAL_SEARCH_MAX_ITEMS = int(os.getenv("SCENECOPILOT_EXTERNAL_SEARCH_MAX_ITEMS", "3"))
OCR_PROVIDER = os.getenv("SCENECOPILOT_OCR_PROVIDER", "local")
VISION_PROVIDER = os.getenv("SCENECOPILOT_VISION_PROVIDER", "local")
RETRIEVAL_PROVIDER = os.getenv("SCENECOPILOT_RETRIEVAL_PROVIDER", "sqlite")
DECISION_PROVIDER = os.getenv("SCENECOPILOT_DECISION_PROVIDER", "local")
SPEECH_PROVIDER = os.getenv("SCENECOPILOT_SPEECH_PROVIDER", "local")
EMBEDDING_PROVIDER = os.getenv("SCENECOPILOT_EMBEDDING_PROVIDER", "local_hash")
ALIGNMENT_WINDOW_MS = int(os.getenv("SCENECOPILOT_ALIGNMENT_WINDOW_MS", "4000"))
ALIGNMENT_FUTURE_TOLERANCE_MS = int(os.getenv("SCENECOPILOT_ALIGNMENT_FUTURE_TOLERANCE_MS", "750"))
ALIGNMENT_MAX_AUDIO_WINDOWS = int(os.getenv("SCENECOPILOT_ALIGNMENT_MAX_AUDIO_WINDOWS", "3"))
WATCHER_HANDLED_TTL_SEC = float(os.getenv("SCENECOPILOT_WATCHER_HANDLED_TTL_SEC", "180"))
SCAN_AGGREGATION_DELAY_MS = int(os.getenv("SCENECOPILOT_SCAN_AGGREGATION_DELAY_MS", "700"))
SCAN_AGGREGATION_MAX_FRAMES = int(os.getenv("SCENECOPILOT_SCAN_AGGREGATION_MAX_FRAMES", "3"))
SCAN_AGGREGATION_SCENE_GAP_MS = int(os.getenv("SCENECOPILOT_SCAN_AGGREGATION_SCENE_GAP_MS", "1800"))
SCAN_WINDOW_TTL_SEC = float(os.getenv("SCENECOPILOT_SCAN_WINDOW_TTL_SEC", "20"))
